name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: move to Frontend directory
        run: cd WhoAmI-Today-frontend

      - name: Install dependencies
        run: yarn install

      - name: Build production
        run: yarn run build --prod

      - name: Remove old build directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
	        username: ${{ secrets.SERVER_USER }}
	        key: ${{ secrets.SERVER_KEY }}
          rm: true
          source: "build/"
          target: "~/WhoAmI-Today-frontend"

      - name: Upload new build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
	        username: ${{ secrets.SERVER_USER }}
	        key: ${{ secrets.SERVER_KEY }}
          source: "build/"
          target: "~/WhoAmI-Today-frontend"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
		      host: ${{ secrets.SERVER_HOST }}
	        username: ${{ secrets.SERVER_USER }}
	        key: ${{ secrets.SERVER_KEY }}
          script: sudo systemctl restart nginx
	